.TH kwekash 1 "April 2025" "kwekash 1.0" "User Commands"
.SH NAME
kwekash \- run weka commands inside a WEKA drive pod

.SH SYNOPSIS
kwekash [-it] [weka_subcommand]

.SH DESCRIPTION
This tool allows you to run weka CLI commands inside the first available WEKA drive pod
in your Kubernetes cluster.

.SH OPTIONS
.TP
-it
Open an interactive shell in the drive pod.

.SH EXAMPLES
.TP
kwekash
Run "weka status" on the pod.

.TP
kwekash -it
Start an interactive shell on the pod.

.TP
kwekash status
Run "weka status" on the pod.

.TP
kwekash local ps
Run "weka local ps" on the pod.

